name: auth_design
description: Simple Authentication Design
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.11.0
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  phone_form_field: ^4.3.1
  pinput: ^3.0.1
  google_sign_in: ^6.1.6

flutter_app_name:
  name: 'Authentication'

flutter_icons:
  android: true  
  ios: true
  min_sdk_android: 21
  image_path: 'images/logo.png'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - images/